version: '2'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    links:
      - devserver
  
  devserver:
    build:
      context: .
      dockerfile: Dockerfile.devserver
    volumes:
      - ../../:/devserver
    command: 'node /devserver/bin/webpack-dev-server.js'
